Repository mozilla/protocol, pull requests merged in 2018-04, with the labels that each got.

#42 Update package.json
  CHANGELOG.md
  src/assets/package/README.md
  src/assets/package/package.json
Labels: Bug :beetle:

#43 Update dependencies
  package-lock.json
  package.json
Labels: Tools :wrench:

#55 Fix font path for typescale demo
  src/assets/sass/demos/type-scale.scss
Labels: Bug :beetle:

#66 Use relative paths in pre-compiled CSS
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/package/README.md
  src/assets/package/package.json
  src/assets/sass/protocol/protocol.scss
Labels: Bug :beetle:

#48 Import colors npm package
  CHANGELOG.md
  gulp/config.js
  gulp/tasks/sass-copy.js
  package-lock.json
  package.json
  src/assets/sass/docs/site.scss
  src/assets/sass/protocol/base/elements/_document.scss
  src/assets/sass/protocol/components/_card.scss
  src/assets/sass/protocol/includes/_colors.scss
  src/assets/sass/protocol/includes/_lib.scss
  src/data/colors.json
Labels: Infra :wrench:
