Repository mozilla/protocol, pull requests merged in 2019-10, with the labels that each got.

#492 CTA links now use text underlines instead of borders (#490)
  CHANGELOG.md
  src/assets/sass/protocol/base/elements/_links.scss
  src/assets/sass/protocol/components/_menu-list.scss
Labels: Needs:Review 👋, P3, Review: XS

#510 Update @mozilla-protocol/assets to 3.0.1 (#509)
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Needs:Review 👋, P1, Review: XS

#502 fixes #489
  CHANGELOG.md
  src/assets/sass/protocol/components/_emphasis-box.scss
  src/patterns/molecules/emphasis-box/medium-emphasis-box.hbs
Labels: Needs:Review 👋, P3, Review: XS

#512 Zap
  CHANGELOG.md
  src/assets/sass/protocol/components/_zap.scss
  src/assets/sass/protocol/includes/_mixins.scss
  src/assets/sass/protocol/includes/mixins/_zap.scss
  src/assets/sass/protocol/protocol-extra.scss
  src/pages/demos/zap.hbs
  src/patterns/atoms/zap/text.hbs
Labels: P1, Review: XS

#514 Menu List Firefox theme CTA uses firefox-font (#503)
  CHANGELOG.md
  src/assets/sass/protocol/components/_menu-list.scss
Labels: Needs:Review 👋, P3, Review: XS

#454 Prism styles consume Protocol Tokens
  CHANGELOG.md
  src/assets/sass/docs/prism.scss
Labels: Needs:Review 👋, P3, Review: XS
