Repository mozilla/protocol, pull requests merged in 2019-02, with the labels that each got.

#277 Billboard overflowing text in IE 10 (Fixes #276)
  CHANGELOG.md
  src/assets/sass/protocol/components/_billboard.scss
Labels: P3, Review: XS

#308 Menu styles tweaks
  CHANGELOG.md
  src/assets/sass/protocol/components/_menu-item.scss
  src/assets/sass/protocol/components/_menu.scss
  src/pages/demos/navigation.hbs
  src/patterns/molecules/menu/menu-item.hbs
Labels: Ready for Review 👋, Review: XS

#314 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: P3, Review: XS

#305 Update ESLint to consume @mozilla-protocol/eslint-config (Fixes #85)
  .eslintrc.js
  CHANGELOG.md
  gulpfile.js/.eslintrc.js
  gulpfile.js/config.js
  gulpfile.js/index.js
  gulpfile.js/tasks/build.js
  gulpfile.js/tasks/clean.js
  gulpfile.js/tasks/compile-sass.js
  gulpfile.js/tasks/compress-css.js
  gulpfile.js/tasks/compress-js.js
  gulpfile.js/tasks/concat-js.js
  gulpfile.js/tasks/copy-js.js
  gulpfile.js/tasks/copy-sass.js
  gulpfile.js/tasks/copy-static.js
  gulpfile.js/tasks/default.js
  gulpfile.js/tasks/drizzle.js
  gulpfile.js/tasks/lint-css.js
  gulpfile.js/tasks/lint-js.js
  gulpfile.js/tasks/serve.js
  gulpfile.js/tasks/test.js
  gulpfile.js/tasks/watch.js
  gulpfile.js/utils/handleErrors.js
  package-lock.json
  package.json
  src/assets/js/protocol/protocol-details.js
  src/assets/js/protocol/protocol-lang-switcher.js
  src/assets/js/protocol/protocol-menu.js
  src/assets/js/protocol/protocol-modal.js
  src/assets/js/protocol/protocol-navigation.js
  src/assets/js/protocol/protocol-sidemenu.js
  src/assets/js/protocol/protocol-supports.js
  src/assets/js/protocol/protocol-utils.js
  stylelint.config.js
  tests/karma.conf.js
  tests/unit/protocol-details.js
  tests/unit/protocol-lang-switcher.js
  tests/unit/protocol-menu.js
  tests/unit/protocol-navigation.js
Labels: P2, Review: S

#301 Add base <hr> styles (#296)
  CHANGELOG.md
  src/assets/sass/protocol/base/elements/_sections.scss
Labels: Ready for Review 👋, Review: XS

#302 Define basic dl styles (#295)
  CHANGELOG.md
  src/assets/sass/protocol/base/elements/_lists.scss
  src/patterns/atoms/typographic/lists.hbs
Labels: Ready for Review 👋, Review: XS

#318 Don't repeat social icons (Fix #317)
  CHANGELOG.md
  src/assets/sass/protocol/components/_footer.scss
Labels: Ready for Review 👋, Review: XS

#321 Make the Menu molecule more resilient to JS errors (Fixes #320)
  CHANGELOG.md
  src/assets/js/protocol/protocol-menu.js
  src/assets/js/protocol/protocol-navigation.js
  src/assets/sass/protocol/components/_menu.scss
  src/assets/sass/protocol/components/_navigation.scss
  src/patterns/molecules/menu/menu.hbs
  tests/unit/protocol-menu.js
  tests/unit/protocol-navigation.js
Labels: P3, Review: XS

#309 Enable second navigation menu on pages (#300)
  CHANGELOG.md
  src/assets/js/protocol/protocol-navigation.js
  src/pages/demos/navigation.hbs
  src/patterns/organisms/navigation/navigation.hbs
Labels: Ready for Review 👋, Review: S

#328 Update deployment docs
  docs/README.md
Labels: Ready for Review 👋, Review: XS

#325 Add optional label to navigation mobile menu button. #313
  CHANGELOG.md
  src/assets/sass/protocol/components/_navigation.scss
  src/pages/demos/navigation.hbs
  src/patterns/organisms/navigation/navigation.hbs
Labels: Ready for Review 👋, Review: XS
