Repository mozilla/protocol, pull requests merged in 2020-04, with the labels that each got.

#555 Add title size utility class (#297)
  CHANGELOG.md
  src/assets/sass/demos/hero.scss
  src/assets/sass/demos/type-scale.scss
  src/assets/sass/docs/site.scss
  src/assets/sass/protocol/base/elements/_forms.scss
  src/assets/sass/protocol/base/elements/_quotes.scss
  src/assets/sass/protocol/base/elements/_typography.scss
  src/assets/sass/protocol/base/utilities/_typography.scss
  src/assets/sass/protocol/components/_article.scss
  src/assets/sass/protocol/components/_billboard.scss
  src/assets/sass/protocol/components/_call-out.scss
  src/assets/sass/protocol/components/_card.scss
  src/assets/sass/protocol/components/_feature-card.scss
  src/assets/sass/protocol/components/_hero.scss
  src/assets/sass/protocol/components/_menu-item.scss
  src/assets/sass/protocol/components/_modal.scss
  src/assets/sass/protocol/components/_newsletter-form.scss
  src/assets/sass/protocol/components/_picto-card.scss
  src/assets/sass/protocol/includes/mixins/_typography.scss
  src/assets/sass/protocol/protocol.scss
  src/pages/fundamentals/typography.hbs
  src/patterns/atoms/typographic/headings.hbs
Labels: Needs:Review 👋, Review: XS

#561 Implement sticky navigation (Fixes #560)
  CHANGELOG.md
  src/assets/js/protocol/protocol-navigation.js
  src/assets/js/protocol/protocol-supports.js
  src/assets/sass/protocol/components/_navigation.scss
  src/pages/demos/navigation.hbs
  src/patterns/organisms/navigation/navigation.hbs
  tests/unit/protocol-navigation.js
Labels: P1

#566 Update form label styles (#430)
  CHANGELOG.md
  src/assets/sass/protocol/base/elements/_forms.scss
  src/assets/sass/protocol/base/elements/_reset.scss
  src/assets/sass/protocol/base/elements/_typography.scss
  src/assets/sass/protocol/includes/forms/_lib.scss
Labels: Needs:Review 👋, Review: XS

#564 Add styled select drop downs (#435)
  CHANGELOG.md
  src/assets/sass/protocol/base/elements/_forms.scss
  src/assets/sass/protocol/includes/_mixins.scss
  src/assets/sass/protocol/includes/forms/_lib.scss
  src/assets/sass/protocol/includes/mixins/_images.scss
Labels: Review: XS

#562 Updated button styles (#429)
  CHANGELOG.md
  src/assets/sass/docs/site.scss
  src/assets/sass/protocol/components/_button.scss
  src/assets/sass/protocol/includes/forms/_lib.scss
  src/pages/demos/emphasis-box.hbs
  src/patterns/atoms/buttons/disabled.hbs
  src/patterns/atoms/buttons/neutral-dark.hbs
  src/patterns/atoms/buttons/neutral.hbs
  src/patterns/atoms/buttons/overview.hbs
  src/patterns/atoms/buttons/primary-dark.hbs
  src/patterns/atoms/buttons/primary.hbs
  src/patterns/atoms/buttons/product-secondary-dark.hbs
  src/patterns/atoms/buttons/product-secondary.hbs
  src/patterns/atoms/buttons/product.hbs
  src/patterns/atoms/buttons/secondary-dark.hbs
  src/patterns/atoms/buttons/secondary.hbs
  src/patterns/atoms/buttons/sizes.hbs
  src/patterns/atoms/lists/inline-lists.hbs
  src/patterns/molecules/download-button/download-button-secondary.hbs
  src/patterns/organisms/navigation/navigation.hbs
Labels: Review: XS

#565 Add styled text inputs (#430)
  CHANGELOG.md
  src/assets/sass/protocol/base/elements/_forms.scss
  src/assets/sass/protocol/base/elements/_reset.scss
  src/assets/sass/protocol/includes/mixins/_images.scss
  src/pages/demos/newsletter.hbs
  src/patterns/atoms/forms/errors.hbs
  src/patterns/atoms/forms/other-input.hbs
  src/patterns/organisms/newsletter/newsletter.hbs
Labels: Needs:Review 👋, Review: XS

#570 center the notification bar in larger viewports
  CHANGELOG.md
  src/assets/sass/protocol/components/_notification-bar.scss
Labels: Needs:Review 👋, Review: µ

#571 Button line-height bug fix
  CHANGELOG.md
  src/assets/sass/protocol/components/_button.scss
Labels: Review: µ

#572 Form SCSS cleanup
  CHANGELOG.md
  src/assets/sass/protocol/base/elements/_forms.scss
  src/assets/sass/protocol/base/elements/_reset.scss
Labels: Review: µ

#569 Tweak form error styles (#508)
  CHANGELOG.md
  src/assets/sass/protocol/base/elements/_forms.scss
  src/patterns/atoms/forms/errors.hbs
Labels: Review: XS
