Repository mozilla/protocol, pull requests merged in 2020-06, with the labels that each got.

#586 Update form spacing and add form layout components
  CHANGELOG.md
  docs/README.md
  src/assets/sass/demos/forms.scss
  src/assets/sass/docs/site.scss
  src/assets/sass/protocol/base/elements/_forms.scss
  src/assets/sass/protocol/components/forms/_field.scss
  src/assets/sass/protocol/components/forms/_form.scss
  src/assets/sass/protocol/components/forms/_set.scss
  src/assets/sass/protocol/includes/forms/_lib.scss
  src/assets/sass/protocol/protocol-extra.scss
  src/pages/demos/forms/accounts.hbs
  src/pages/demos/forms/long.hbs
  src/patterns/atoms/forms/base.hbs
  src/patterns/atoms/forms/field-note.hbs
  src/patterns/atoms/forms/fieldset.hbs
  src/patterns/atoms/forms/heading.hbs
  src/patterns/molecules/forms/collection.yml
  src/patterns/molecules/forms/field.hbs
  src/patterns/molecules/forms/fields/input.hbs
  src/patterns/molecules/forms/fields/list.hbs
  src/patterns/molecules/forms/fields/select.hbs
  src/patterns/molecules/forms/fields/textarea.hbs
  src/patterns/molecules/forms/header-footer.hbs
  src/patterns/molecules/forms/set.hbs
  src/patterns/templates/forms/form-spacing.hbs
  src/templates/drizzle/item.hbs
Labels: P2, Review: XS

#599 Update gulp-sass to v4.1.0 (Fixes #598)
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Needs:Review 👋, Review: µ

#595 [fix #505] New content layout containers
  CHANGELOG.md
  src/assets/sass/demos/content-container.scss
  src/assets/sass/protocol/base/elements/_sections.scss
  src/data/specimens.yaml
  src/pages/demos/content-container-vis.hbs
  src/pages/demos/content-containers.hbs
  src/patterns/organisms/call-out/call-out.hbs
  src/patterns/organisms/footer/includes/footer-random.hbs
  src/patterns/organisms/hero/hero.hbs
  src/patterns/templates/content-container/content-container.hbs
  src/patterns/templates/content-layout/small-content-layout.hbs
Labels: Review: S

#606 Icons page: update intro, de-list from nav
  src/pages/fundamentals/icons.hbs
Labels: Blocker :no_entry:
