Repository mozilla/protocol, pull requests merged in 2020-07, with the labels that each got.

#610 Typo in card docs
  src/patterns/molecules/card/large-card.hbs
Labels: Needs:Review 👋, P1, Review: µ

#612 [fix #611] Reduce content container min-width
  CHANGELOG.md
  src/assets/sass/protocol/base/elements/_sections.scss
Labels: Needs:Review 👋, Review: µ

#619 Set text align on image replacement mixin Fix #618
  CHANGELOG.md
  src/assets/sass/protocol/includes/_mixins.scss
Labels: Needs:Review 👋, P1, Review: µ

#617 Navigation is max-content width on large screens (#615)
  CHANGELOG.md
  src/assets/sass/protocol/components/_navigation.scss
Labels: Needs:Review 👋, P1, Review: XS

#614 Decrease min-width of form fields.
  CHANGELOG.md
  src/assets/sass/protocol/includes/forms/_lib.scss
Labels: Needs:Review 👋, Review: XS

#621 Remove max-width from cards in card-layout (Fix #620)
  CHANGELOG.md
  src/assets/sass/protocol/components/_card.scss
  src/assets/sass/protocol/templates/_card-layout.scss
Labels: Needs:Review 👋, P1, Review: XS

#625 Add sticky promo component (#603)
  CHANGELOG.md
  src/assets/js/protocol/protocol-sticky-promo.js
  src/assets/sass/protocol/base/includes/_animations.scss
  src/assets/sass/protocol/components/_sticky-promo.scss
  src/assets/sass/protocol/protocol-extra.scss
  src/patterns/molecules/sticky-promo/sticky-promo.hbs
Labels: Review: S
