Repository mozilla/protocol, pull requests merged in 2021-08, with the labels that each got.

#704 Picto bottom margins in multi-column [fix #699]
  CHANGELOG.md
  src/assets/sass/protocol/components/_picto.scss
Labels: Needs:Review 👋, Review: µ

#703 Enhancements/fixes for Split component [fix #702]
  CHANGELOG.md
  src/assets/sass/protocol/base/elements/_containers.scss
  src/assets/sass/protocol/components/_split.scss
  src/patterns/organisms/split/split.hbs
Labels: Review: XS, Needs:Review 👋

#698 Update docs to clarify brand variable use (fixes #697)
  CHANGELOG.md
  src/pages/fundamentals/themes.md
Labels: P3, Needs:Review 👋, Review: µ
