Repository mozilla/protocol, pull requests merged in 2021-04, with the labels that each got.

#672 New picto component [fix #382] and multi-column layout [fix #233]
  CHANGELOG.md
  src/assets/sass/demos/columns.scss
  src/assets/sass/demos/picto.scss
  src/assets/sass/protocol/components/_picto.scss
  src/assets/sass/protocol/protocol-components.scss
  src/assets/sass/protocol/templates/_multi-column.scss
  src/pages/demos/columns.hbs
  src/pages/demos/picto.hbs
  src/patterns/molecules/picto-card/picto-card-compact.hbs
  src/patterns/molecules/picto-card/picto-card.hbs
  src/patterns/molecules/picto/picto-center.hbs
  src/patterns/molecules/picto/picto-side.hbs
  src/patterns/molecules/picto/picto.hbs
  src/patterns/templates/columns/columns.hbs
  src/patterns/templates/content-container/content-container.hbs
  src/static/img/picto/image.svg
Labels: Review: S

#675 Add Split Block
  CHANGELOG.md
  src/assets/sass/demos/split.scss
  src/assets/sass/protocol/components/_split.scss
  src/assets/sass/protocol/protocol-components.scss
  src/pages/demos/split-visual.hbs
  src/pages/demos/split.hbs
  src/patterns/organisms/split/collection.yml
  src/patterns/organisms/split/split-bg.hbs
  src/patterns/organisms/split/split.hbs
  src/static/img/split/add-ons.png
  src/static/img/split/devices-high-res.png
  src/static/img/split/devices.png
  src/static/img/split/image.png
Labels: Review: L

#677 Reduce base heading sizes [no bug]
  CHANGELOG.md
  src/assets/sass/docs/site.scss
  src/assets/sass/protocol/base/elements/_titles.scss
  src/assets/sass/protocol/components/_article.scss
  src/pages/demos/theme-firefox.hbs
  src/pages/demos/theme-mozilla.hbs
Labels: Needs:Review 👋, Review: XS

#678 Bump version to 14.0.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/package/README.md
  src/assets/package/package.json
Labels: Needs:Review 👋, Review: µ

#683 Fix footer logo, bump version to 14.0.3
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/package/README.md
  src/assets/package/package.json
  src/assets/sass/protocol/components/_footer.scss
Labels: Bug :beetle:
