Repository mozilla/protocol, pull requests merged in 2021-11, with the labels that each got.

#737 Correct Split docs, body width class goes on the container
  src/patterns/organisms/split/split.hbs
Labels: Bug :beetle:, Documentation :memo:, Review: µ

#740 Bump version to 15.1.0
  CHANGELOG.md
  package.json
  src/assets/package/README.md
  src/assets/package/package.json
Labels: Needs:Review 👋

#730 Create new breadcrumb component
  CHANGELOG.md
  src/assets/sass/protocol/components/_breadcrumb.scss
  src/assets/sass/protocol/protocol-components.scss
  src/patterns/molecules/breadcrumb/breadcrumb.hbs
Labels: P2, Review: S, Needs:Review 👋, Documentation :memo:

#741 Add tertiary theme color, rename alt to secondary
  CHANGELOG.md
  src/assets/sass/demos/theme-firefox.scss
  src/assets/sass/demos/theme-mozilla.scss
  src/assets/sass/protocol/base/elements/_quotes.scss
  src/assets/sass/protocol/base/utilities/_backgrounds.scss
  src/assets/sass/protocol/components/_breadcrumb.scss
  src/assets/sass/protocol/components/_call-out.scss
  src/assets/sass/protocol/components/_feature-card.scss
  src/assets/sass/protocol/components/_hero.scss
  src/assets/sass/protocol/components/_picto-card.scss
  src/assets/sass/protocol/components/forms/_form.scss
  src/assets/sass/protocol/includes/_themes.scss
  src/assets/sass/protocol/includes/forms/_lib.scss
  src/pages/demos/theme-firefox.hbs
  src/pages/demos/theme-mozilla.hbs
  src/pages/docs/contributing.md
  src/pages/fundamentals/themes.md
Labels: Review: XS, Needs:Review 👋

#743 Fix image overlapping content in a reversed Split with media overflow
  CHANGELOG.md
  src/assets/sass/protocol/components/_split.scss
Labels: Bug :beetle:, Needs:Review 👋, Review: µ

#744 Bump version to 16.0.0
  CHANGELOG.md
  package.json
  src/assets/package/README.md
  src/assets/package/package.json
Labels: Review: µ
