Repository mozilla/protocol, pull requests merged in 2022-06, with the labels that each got.

#788 Add notification bar
  components/notification-bar/notification-bar--scripted.html
  components/notification-bar/notification-bar--scripted.readme.md
  components/notification-bar/notification-bar--sticky.html
  components/notification-bar/notification-bar--sticky.readme.md
  components/notification-bar/notification-bar.config.yml
  components/notification-bar/notification-bar.html
  components/notification-bar/readme.md
Labels: Review: XS, Needs:Review 👋

#789 Migrate Picto Card
  components/picto-card/picto-card.config.yml
  components/picto-card/picto-card.html
  components/picto-card/readme.md
  components/picto/readme.md
Labels: Review: XS, Needs:Review 👋

#794 Fixed broken link in Content Containers page
  src/patterns/templates/content-container/content-container.hbs
Labels: Bug :beetle:, Needs:Review 👋, Review: µ

#792 Make sure to build package using production mode
  CHANGELOG.md
  package.json
Labels: Needs:Review 👋

#795 Migrate Sticky Promo
  components/sticky-promo/readme.md
  components/sticky-promo/sticky-promo.config.yml
  components/sticky-promo/sticky-promo.html
Labels: Review: XS, Needs:Review 👋

#786 Some components migration into Fractal
  components/article/article.html
  components/article/readme.md
  components/breadcrumb/breadcrumb.html
  components/breadcrumb/readme.md
  components/content-container/content-container.config.yml
  components/content-container/content-container.html
  components/content-container/readme.md
  components/forms/02-select/select.config.yml
  components/language-switcher/language-switcher.html
  components/language-switcher/readme.md
  components/menu-list/menu-list--download.html
  components/menu-list/menu-list.config.yml
  components/menu-list/menu-list.html
  components/menu-list/readme.md
Labels: Size: XS, Needs:Review 👋, Documentation :memo:

#793 Migrate Cards and Feature Card
  components/_preview-dark.html
  components/card/card.config.yml
  components/card/card.html
  components/card/readme.md
  components/feature-card/feature-card.config.yml
  components/feature-card/feature-card.html
  components/feature-card/readme.md
  static/img/image-3-2-high-res.jpg
  static/img/image-3-2.jpg
Labels: Review: XS

#796 Migrate download button
  components/download-button/download-button--secondary.html
  components/download-button/download-button.config.yml
  components/download-button/download-button.html
  components/download-button/readme.md
Labels: Needs:Review 👋, Review: µ

#797 Add card layout and columns, reorg other layout templates
  components/card/card.config.yml
  components/layout/01-content-container/content-container.config.yml
  components/layout/01-content-container/content-container.html
  components/layout/01-content-container/readme.md
  components/layout/02-columns/columns--four.html
  components/layout/02-columns/columns--three.html
  components/layout/02-columns/columns--two.html
  components/layout/02-columns/columns.config.yml
  components/layout/02-columns/columns.html
  components/layout/02-columns/readme.md
  components/layout/03-card-layout/02-card-layout--third.html
  components/layout/03-card-layout/03-card-layout--quarter.html
  components/layout/03-card-layout/04-card-layout--hero.html
  components/layout/03-card-layout/card-layout.config.yml
  components/layout/03-card-layout/card-layout.html
  components/layout/03-card-layout/readme.md
  components/layout/04-main-with-sidebar/01-main-with-sidebar/main-with-sidebar.config.yml
  components/layout/04-main-with-sidebar/01-main-with-sidebar/main-with-sidebar.html
  components/layout/04-main-with-sidebar/01-main-with-sidebar/readme.md
  components/layout/04-main-with-sidebar/example-sidebar-menu/example-sidebar-menu.html
  components/layout/04-main-with-sidebar/example-sidebar-menu/readme.md
Labels: Review: XS, Needs:Review 👋

#798 Migrate navigation
  components/download-button/download-button--secondary.html
  components/download-button/download-button.config.yml
  components/navigation/01-navigation/navigation.config.yml
  components/navigation/01-navigation/navigation.html
  components/navigation/01-navigation/readme.md
  components/navigation/02-menu/menu.html
  components/navigation/02-menu/readme.md
  components/navigation/03-menu-item/menu-item.config.yml
  components/navigation/03-menu-item/menu-item.html
  components/navigation/03-menu-item/readme.md
Labels: Review: S, Needs:Review 👋

#799 Migrate Modal and Billboard components to Fractal
  components/billboard/billboard.html
  components/billboard/readme.md
  components/modal/modal.html
  components/modal/readme.md
  static/img/billboard-image.png
Labels: Review: XS, Needs:Review 👋

#802 Add direction toggle
  .eslintrc.js
  theme/assets/js/bidi.js
  theme/assets/sass/components/_pen.scss
  theme/assets/sass/preview.scss
  theme/views/partials/pen/header.nunj
  theme/views/partials/scripts.nunj
  webpack.docs.build.config.js
Labels: Review: XS, Needs:Review 👋

#806 Add tokens doc
  docs/01-fundamentals/05-design-tokens.md
  docs/01-fundamentals/design-tokens.config.yml
  theme/assets/sass/components/_tokens.scss
  theme/assets/sass/theme.scss
Labels: Review: XS, Needs:Review 👋

#807 Update contributing doc, add usage docs, general doc tidying
  README.md
  docs/01-fundamentals/01-principles.md
  docs/01-fundamentals/02-themes.md
  docs/01-fundamentals/03-typography.md
  docs/01-fundamentals/04-color.md
  docs/01-fundamentals/05-design-tokens.md
  docs/02-usage/01-overview.md
  docs/02-usage/02-framework.md
  docs/03-contributing/01-overview.md
  docs/03-contributing/02-naming.md
  docs/03-contributing/03-css-guide.md
  theme/assets/sass/components/_browser.scss
  theme/assets/sass/components/_prose.scss
Labels: Review: XS, Needs:Review 👋
